import type { Chapter, StoryLine } from './types';

const CHARACTER_IMAGES: Record<string, string> = {
  大賢者アウレリア: '大賢者アウレリア.png',
  乾いた村の長老: '乾いた村の長老.png',
  村の治療師: '村の治療師.png',
  旅の商人: '旅の商人.png',
  若き旅人: '若き旅人.png',
  市場の番人: '市場の番人.png',
  村の若者: '村の若者.png',
  砂漠の契約魔導師: '砂漠の契約魔導士.png',
  密約の仲介人: '密約の仲介人.png',
  幻影族の首領: '幻影族の首領.png',
  王国の会計官: '王国の会計官.png',
  監査役の騎士: '監査役の騎士.png',
  迷宮の主の手下: '迷宮の主の手下.png',
  予言者の商人: '預言者の商人.png',
  黄金の暴君: '黄金の暴君.png',
  若き騎士団員: '若き騎士団員.png',
  絶対君主の隊長: '絶対君主の隊長.png',
  森の妖精: '森の妖精.png',
  毒霧族の策士: '毒霧族の策士.png',
  新任の騎士: '新任の騎士.png',
  通報を担う騎士: '通報を担う騎士.png',
  霧の支配者: '霧の支配者.png',
  情報守護官: '情報守護官.png',
  なりすましの密偵: 'なりすましの密偵.png',
  酒場の主人: '酒場の主人.png',
  影の解析者: '影の解析者.png',
  影の参謀: '影の参謀.png',
  時計塔の職人: '時計塔の職人.png',
  現場監督: '現場監督.png',
  怠惰族の幻聴: '怠惰族の幻聴.png',
  時を奪う魔: '時を奪う魔.png',
  魔王コンプラ・ブレイカー: '魔王コンプラ・ブレイカー.png',
  五つの聖域の仲間: '五つの聖域の仲間.png',
};

const ENEMY_IMAGE = '/static/assets/visuals/monster-compendium.png';

const getCharacterImage = (name?: string) => {
  if (!name) return ENEMY_IMAGE;
  const file = CHARACTER_IMAGES[name];
  return file ? `/static/assets/characters/${encodeURIComponent(file)}` : ENEMY_IMAGE;
};

const NPC_IMAGES = {
  sage: getCharacterImage('大賢者アウレリア'),
  villager: getCharacterImage('乾いた村の長老'),
  knight: getCharacterImage('監査役の騎士'),
  clerk: getCharacterImage('王国の会計官'),
  steward: getCharacterImage('五つの聖域の仲間'),
  guard: getCharacterImage('情報守護官'),
  artisan: getCharacterImage('時計塔の職人'),
};

const narrator = (text: string): StoryLine => ({
  role: 'narrator',
  text,
  speakerName: '語り部',
  portrait: getCharacterImage('大賢者アウレリア'),
});

const hero = (text: string, partnerRole: StoryLine['role'] = 'ally'): StoryLine => ({
  role: 'hero',
  text,
  partnerRole,
});

const ally = (text: string, speakerName?: string, portrait?: string): StoryLine => ({
  role: 'ally',
  text,
  speakerName,
  portrait: getCharacterImage(speakerName) || portrait,
});

const enemy = (text: string, speakerName?: string, portrait?: string): StoryLine => ({
  role: 'enemy',
  text,
  speakerName,
  portrait: getCharacterImage(speakerName) || portrait,
});

/**
 * 全ストーリーチャプターデータ
 */
export const chapters: Chapter[] = [
  {
    id: 'prologue',
    title: 'プロローグ',
    subtitle: '目覚めと守護者の印',
    category: '導入',
    narration: [
      narrator('誠実の魔力で栄えたエシカル王国は、いま混沌の霧に覆われている。'),
      narrator('霧は人々の良心を奪い、不祥事モンスターを生み出した。'),
      ally('目覚めたか、{hero}よ。ここは王城の宝物庫だ。', '大賢者アウレリア', NPC_IMAGES.sage),
      hero('あなたは…誰ですか？', 'ally'),
      ally('守護者の証が、君を選んだ。学びと誠実が王国を救う。', '大賢者アウレリア', NPC_IMAGES.sage),
      narrator('水晶は暖かな光を放ち、{hero}の胸に誓いを刻んだ。'),
      hero('僕が王国を救う…。', 'ally'),
      ally('五つの聖域へ向かい、霧の源を浄化するのだ。', '大賢者アウレリア', NPC_IMAGES.sage),
      narrator('王城の門が開く。風は新たな旅の匂いを運んだ。'),
      hero('行こう。守護者として。', 'ally'),
    ],
    stage: '王城・宝物庫',
    monster: 'なし',
    scenario: '守護者としての覚醒',
    playerRole: '守護者の証を受け取り、王国を救う旅に出る',
    cleared: false,
    order: 0,
    quizTriggers: [4],
    ally: {
      name: '大賢者アウレリア',
      image: getCharacterImage('大賢者アウレリア'),
    },
  },
  {
    id: 'chapter1',
    title: '第一章',
    subtitle: '欺瞞の砂漠',
    category: '法務・取引・広告編',
    narration: [
      narrator('第1話「乾いた村の呼び声」乾ききった村に「伝説の聖水」の看板が乱立する。'),
      ally('看板のせいで人が集まり、余計に混乱しているのです。', '乾いた村の長老', NPC_IMAGES.villager),
      hero('表示の真偽を確かめないと、村人が傷つく。', 'ally'),
      narrator('教育テーマ: 景品表示法（広告の基本）'),
      narrator('第2話「最高」の根拠。「万病に効く」と謳う行商人が現れる。'),
      ally('薬草ひとつで治るとまで言い出しました。', '村の治療師', NPC_IMAGES.clerk),
      hero('根拠のない断言は優良誤認になる。', 'ally'),
      narrator('教育テーマ: 優良誤認の禁止'),
      narrator('第3話「期間限定の罠」毎日「今だけ無料」と叫ぶ露店が現れる。'),
      ally('焦らせて買わせるのはズルいですよね…。', '旅の商人', NPC_IMAGES.steward),
      hero('有利誤認やおとり広告は信頼を壊す。', 'ally'),
      narrator('教育テーマ: 有利誤認・おとり広告'),
      narrator('第4話「友情の証という鎖」友好の証と称する契約書に怪しい条項。'),
      ally('署名したら全財産没収と書かれていました!', '若き旅人', NPC_IMAGES.knight),
      hero('契約の内容確認は締結前の義務だ。', 'ally'),
      narrator('教育テーマ: 契約締結時の内容確認義務'),
      narrator('第5話「沈黙の特約」極小文字で他社取引禁止の条件が潜む。'),
      enemy('契約は契約だ。逃げ道はない。', '砂漠の契約魔導師', ENEMY_IMAGE),
      hero('不当な拘束条件は独占禁止法に触れる。', 'enemy'),
      narrator('教育テーマ: 独占禁止法（不当な拘束条件）'),
      narrator('第6話「蜃気楼のロゴ」王室御用達を偽る紋章が砂に浮かぶ。'),
      ally('偽の紋章で信用を奪っているのです。', '市場の番人', NPC_IMAGES.guard),
      hero('商標と不正競争防止の線引きを守ろう。', 'ally'),
      narrator('教育テーマ: 商標権・不正競争防止法'),
      narrator('第7話「甘いキックバック」村役人に高級魔石を渡す密約。'),
      enemy('これで門は開く。感謝しろ。', '密約の仲介人', ENEMY_IMAGE),
      hero('贈収賄は公正な取引を壊す。', 'enemy'),
      narrator('教育テーマ: 贈収賄・不適切な利益供与'),
      narrator('第8話「過大な“おまけ”」水1杯に伝説の魔剣が付く宣伝。'),
      ally('景品が豪華すぎて判断が狂います…。', '村の若者', NPC_IMAGES.villager),
      hero('景品の上限を守らないと公正さが崩れる。', 'ally'),
      narrator('教育テーマ: 景表法（景品制限）'),
      narrator('第9話「決戦! 幻影の首領」虚偽表示と不当契約を操る首領と対峙。'),
      enemy('砂の幻影が真実を飲み込むぞ!', '幻影族の首領', ENEMY_IMAGE),
      hero('矛盾を突き、公正な競争を示す!', 'enemy'),
      narrator('教育テーマ: 公正な競争と誠実な取引'),
      narrator('第10話「誠実のオアシス」正しい表示が信頼を取り戻す。'),
      ally('村に本当の水と笑顔が戻りました。', '乾いた村の長老', NPC_IMAGES.villager),
      hero('消費者の権利と企業の責任が未来を守る。', 'ally'),
      narrator('教育テーマ: 消費者の権利と企業の責任'),
    ],
    stage: '蜃気楼の広がる砂漠',
    monster: '幻影族(ファントム)',
    scenario: '虚偽表示と不当契約の連鎖を断つ',
    playerRole: '正しい表示と公正な取引で砂漠を浄化する',
    cleared: false,
    order: 1,
    quizTriggers: [3, 7, 11, 15, 19, 23, 27, 31, 35, 39],
    ally: {
      name: '乾いた村の長老',
      image: getCharacterImage('乾いた村の長老'),
    },
    enemy: {
      name: '幻影族の首領',
      image: getCharacterImage('幻影族の首領'),
    },
  },
  {
    id: 'chapter2',
    title: '第二章',
    subtitle: '強欲の地下迷宮',
    category: '経理・内部統制編',
    narration: [
      narrator('第1話「消えた王国の金貨」公共事業の資金が消えた。'),
      ally('帳簿に穴が空き、村の橋が止まりました。', '王国の会計官', NPC_IMAGES.clerk),
      hero('資産の保全こそ会計の使命だ。', 'ally'),
      narrator('教育テーマ: 資産の保全と会計の役割'),
      narrator('第2話「黄金の迷宮への誘い」主が国の予算で私邸を築く。'),
      ally('内部統制が崩れているのです。', '監査役の騎士', NPC_IMAGES.knight),
      hero('統制の仕組みが不正を防ぐ。', 'ally'),
      narrator('教育テーマ: 内部統制の基本概念'),
      narrator('第3話「独断という名の魔力」印章を勝手に使う者が現れる。'),
      ally('承認の印が独り歩きしています。', '王国の会計官', NPC_IMAGES.clerk),
      hero('職務分掌で実行と承認を分けるべきだ。', 'ally'),
      narrator('教育テーマ: 職務分掌（実行と承認の分離）'),
      narrator('第4話「消失した稟議書」記録のない支出が続く。'),
      ally('事後承認の言い訳では通りません。', '監査役の騎士', NPC_IMAGES.knight),
      hero('稟議フローと正当な決裁が必要だ。', 'ally'),
      narrator('教育テーマ: 稟議フローと正当な決裁'),
      narrator('第5話「私物化された聖遺物」公費の備品が私邸に。'),
      enemy('国のためなら私が使ってもいいだろう?', '迷宮の主の手下', ENEMY_IMAGE),
      hero('公私混同は信頼を失わせる。', 'enemy'),
      narrator('教育テーマ: 公私混同の禁止・資産管理'),
      narrator('第6話「二重帳簿の魔力」二種類の帳簿が存在する。'),
      ally('表向きの報告と裏帳簿が違います。', '王国の会計官', NPC_IMAGES.clerk),
      hero('帳簿の適正管理が不正会計を防ぐ。', 'ally'),
      narrator('教育テーマ: 不正会計・帳簿の適正管理'),
      narrator('第7話「予言者の取引」未公表の政策を利用する者。'),
      enemy('先に知った者が勝つのだ。', '予言者の商人', ENEMY_IMAGE),
      hero('インサイダー取引は正義ではない。', 'enemy'),
      narrator('教育テーマ: インサイダー取引の禁止'),
      narrator('第8話「架空の遠征報告」偽領収書で裏金を作る。'),
      ally('遠征報告が実在しません。', '監査役の騎士', NPC_IMAGES.knight),
      hero('架空経費は即座に是正すべきだ。', 'ally'),
      narrator('教育テーマ: 架空経費・不正請求の防止'),
      narrator('第9話「決戦! 黄金の暴君」スピードを盾に統制を無視する。'),
      enemy('速さこそ正義だ! 誰も止められぬ!', '黄金の暴君', ENEMY_IMAGE),
      hero('透明性と相互牽制が王国を守る!', 'enemy'),
      narrator('教育テーマ: 経営の透明性と相互牽制'),
      narrator('第10話「清廉なる硬貨」正しい稟議と監査が富を循環させる。'),
      ally('信用が戻れば、王国は再び栄えます。', '王国の会計官', NPC_IMAGES.clerk),
      hero('社会的信用こそ最大の財産だ。', 'ally'),
      narrator('教育テーマ: 社会的信用の維持'),
    ],
    stage: '金貨に埋め尽くされた迷宮',
    monster: '強欲族(グリーディ)',
    scenario: '内部統制を破り、公金を私物化する脅威',
    playerRole: '透明な会計と牽制で迷宮を浄化する',
    cleared: false,
    order: 2,
    quizTriggers: [3, 7, 11, 15, 19, 23, 27, 31, 35, 39],
    ally: {
      name: '王国の会計官',
      image: getCharacterImage('王国の会計官'),
    },
    enemy: {
      name: '黄金の暴君',
      image: getCharacterImage('黄金の暴君'),
    },
  },
  {
    id: 'chapter3',
    title: '第三章',
    subtitle: '沈黙の毒霧の森',
    category: '人事・ハラスメント編',
    narration: [
      narrator('第1話「声の消えた騎士団」兵士たちの目から光が消える。'),
      ally('命令は絶対だと言われ、何も言えません。', '若き騎士団員', NPC_IMAGES.knight),
      hero('組織風土が人を縛っている。', 'ally'),
      narrator('教育テーマ: 組織風土とコンプライアンス'),
      narrator('第2話「毒霧の正体」人格否定の言葉が霧となる。'),
      ally('言葉が胸に刺さり、動けません。', '若き騎士団員', NPC_IMAGES.knight),
      hero('言葉の暴力は心を壊す。', 'ally'),
      narrator('教育テーマ: 言葉による暴力の影響'),
      narrator('第3話「絶対君主の指導」隊長が暴走し、恐怖で統率する。'),
      enemy('厳しさこそ正義だ! 反論は許さぬ!', '絶対君主の隊長', ENEMY_IMAGE),
      hero('人格否定はパワハラだ。', 'enemy'),
      narrator('教育テーマ: パワーハラスメントの定義'),
      narrator('第4話「孤立する妖精」種族を理由に重要任務から外される。'),
      ally('出自で判断され、居場所がありません。', '森の妖精', NPC_IMAGES.villager),
      hero('差別のない評価が必要だ。', 'ally'),
      narrator('教育テーマ: 差別禁止・不当な評価'),
      narrator('第5話「心理的安全性の光」相談できる場が霧を晴らす。'),
      ally('相談できれば救われるのに…。', '若き騎士団員', NPC_IMAGES.knight),
      hero('心理的安全性は信頼の源だ。', 'ally'),
      narrator('教育テーマ: 心理的安全性の確保'),
      narrator('第6話「歪んだ競争心」仲間を貶める不誠実な出世欲。'),
      enemy('蹴落としてこそ評価が上がる!', '毒霧族の策士', ENEMY_IMAGE),
      hero('チームワークと倫理が勝利を呼ぶ。', 'enemy'),
      narrator('教育テーマ: チームワークと倫理的行動'),
      narrator('第7話「無意識の偏見」何気ない言葉が壁を作る。'),
      ally('新人だからと言われると心が折れます。', '新任の騎士', NPC_IMAGES.knight),
      hero('アンコンシャス・バイアスに気づこう。', 'ally'),
      narrator('教育テーマ: アンコンシャス・バイアス'),
      narrator('第8話「沈黙を破る笛」匿名通報の笛が霧を切り裂く。'),
      ally('この笛があれば、声を上げられます。', '通報を担う騎士', NPC_IMAGES.guard),
      hero('内部通報制度は守護の盾だ。', 'ally'),
      narrator('教育テーマ: 内部通報制度の重要性'),
      narrator('第9話「決戦! 霧の支配者」恐怖で秩序を守るボス。'),
      enemy('恐怖こそ秩序だ! 震えて従え!', '霧の支配者', ENEMY_IMAGE),
      hero('敬意と人権尊重で立ち向かう!', 'enemy'),
      narrator('教育テーマ: 人権の尊重と人格の肯定'),
      narrator('第10話「風通しの良い森」霧が晴れ、多様な個性が輝く。'),
      ally('ようやく息ができる森になりました。', '若き騎士団員', NPC_IMAGES.knight),
      hero('多様性こそ最強のチームだ。', 'ally'),
      narrator('教育テーマ: 多様性（D&I）の推進'),
    ],
    stage: '毒霧の漂う静寂の森',
    monster: '毒霧族(ミストウォーカー)',
    scenario: '恐怖と沈黙を生む毒霧の浄化',
    playerRole: '敬意ある対話で森の信頼を取り戻す',
    cleared: false,
    order: 3,
    quizTriggers: [3, 7, 11, 15, 19, 23, 27, 31, 35, 39],
    ally: {
      name: '若き騎士団員',
      image: getCharacterImage('若き騎士団員'),
    },
    enemy: {
      name: '霧の支配者',
      image: getCharacterImage('霧の支配者'),
    },
  },
  {
    id: 'chapter4',
    title: '第四章',
    subtitle: '影の包囲網',
    category: '情シス・情報漏洩編',
    narration: [
      narrator('第1話「漏れ出した国家機密」作戦計画が敵に筒抜け。'),
      ally('どこから漏れたのか調査が必要です。', '情報守護官', NPC_IMAGES.guard),
      hero('情報資産の重要性を示そう。', 'ally'),
      narrator('教育テーマ: 情報資産の重要性'),
      narrator('第2話「城壁の隙間」鍵の閉め忘れが危機を招く。'),
      ally('書類が机に放置されていました。', '情報守護官', NPC_IMAGES.guard),
      hero('物理的なセキュリティは基本だ。', 'ally'),
      narrator('教育テーマ: 物理的・環境的セキュリティ'),
      narrator('第3話「拾った魔道具」怪しい魔石が端末を汚染する。'),
      ally('不明な媒体は絶対に接続してはなりません。', '情報守護官', NPC_IMAGES.guard),
      hero('外部媒体の扱いには慎重さが必要だ。', 'ally'),
      narrator('教育テーマ: ウイルス感染・外部媒体の禁止'),
      narrator('第4話「なりすましの術」偽の王令で合言葉を聞き出す。'),
      enemy('王命だ。合言葉を伝えよ。', 'なりすましの密偵', ENEMY_IMAGE),
      hero('フィッシングの罠は見破る!', 'enemy'),
      narrator('教育テーマ: フィッシング詐欺・標的型攻撃'),
      narrator('第5話「情報の格付け」何が機密か区別できない兵士。'),
      ally('機密の分類が曖昧で、混乱しています。', '情報守護官', NPC_IMAGES.guard),
      hero('情報の格付け管理を徹底しよう。', 'ally'),
      narrator('教育テーマ: 情報の格付け管理'),
      narrator('第6話「噂話の鳥」酒場の愚痴が敵に渡る。'),
      ally('不用意な発言が敵の耳に届きました。', '酒場の主人', NPC_IMAGES.villager),
      hero('SNSや社外発言には注意が必要だ。', 'ally'),
      narrator('教育テーマ: SNS利用・社外での発言注意'),
      narrator('第7話「暗号の劣化」古すぎる結界が破られる。'),
      enemy('古い合言葉はすでに解いた。', '影の解析者', ENEMY_IMAGE),
      hero('パスワード管理の更新が鍵だ。', 'enemy'),
      narrator('教育テーマ: パスワード管理の徹底'),
      narrator('第8話「魔導通信の乱用」公務の水晶球を私用に。'),
      ally('私的利用から隙を突かれました。', '情報守護官', NPC_IMAGES.guard),
      hero('貸与機器の私的利用は禁止だ。', 'ally'),
      narrator('教育テーマ: 貸与機器の私的利用禁止'),
      narrator('第9話「決戦! 影の参謀」データの隙から侵入する敵。'),
      enemy('見えぬ隙こそ勝利の鍵だ。', '影の参謀', ENEMY_IMAGE),
      hero('手順遵守で隙を塞ぐ!', 'enemy'),
      narrator('教育テーマ: 手順遵守（標準化）の重要性'),
      narrator('第10話「鉄壁の盾」全軍がルールを守り防壁を強化。'),
      ally('守るべき手順を徹底します。', '情報守護官', NPC_IMAGES.guard),
      hero('組織的な情報漏洩防止が盾となる。', 'ally'),
      narrator('教育テーマ: 情報漏洩防止の組織的徹底'),
    ],
    stage: '暗闇に包まれた城下町',
    monster: '密偵族(スパイ・シャドウ)',
    scenario: '情報漏洩の脅威に対抗する',
    playerRole: '手順遵守で王国の機密を守る',
    cleared: false,
    order: 4,
    quizTriggers: [3, 7, 11, 15, 19, 23, 27, 31, 35, 39],
    ally: {
      name: '情報守護官',
      image: getCharacterImage('情報守護官'),
    },
    enemy: {
      name: '影の参謀',
      image: getCharacterImage('影の参謀'),
    },
  },
  {
    id: 'chapter5',
    title: '第五章',
    subtitle: '歪んだ時計塔',
    category: '労務・健康管理編',
    narration: [
      narrator('第1話「止まらない時計」職人たちが眠れず倒れていく。'),
      ally('休めずに働き続け、光が消えています。', '時計塔の職人', NPC_IMAGES.artisan),
      hero('労働時間と健康は直結している。', 'ally'),
      narrator('教育テーマ: 労働時間と健康の関係'),
      narrator('第2話「深夜の灯火」寝ずに働くことが忠誠とされる。'),
      ally('36協定を知らぬまま働かされています。', '時計塔の職人', NPC_IMAGES.artisan),
      hero('過重労働は許されない。', 'ally'),
      narrator('教育テーマ: 36協定・過重労働の防止'),
      narrator('第3話「壊れた歯車」熟練者が倒れ、誰も代われない。'),
      ally('代わりがいないから、塔が暴走します。', '時計塔の職人', NPC_IMAGES.artisan),
      hero('属人化のリスクを分散しよう。', 'ally'),
      narrator('教育テーマ: 属人化のリスクと業務分散'),
      narrator('第4話「休息の罪悪感」休む者を責める幻聴が響く。'),
      enemy('休む者は裏切り者だ!', '怠惰族の幻聴', ENEMY_IMAGE),
      hero('セルフケアを否定する声に抗おう。', 'enemy'),
      narrator('教育テーマ: メンタルヘルス・セルフケア'),
      narrator('第5話「管理者の怠慢」上層部が疲弊を見ない。'),
      ally('納期だけが押し付けられています。', '現場監督', NPC_IMAGES.guard),
      hero('安全配慮義務を果たすべきだ。', 'ally'),
      narrator('教育テーマ: 安全配慮義務・監督責任'),
      narrator('第6話「命の砂時計」残業時間がHPを削っていく。'),
      ally('限界を超えると、命が削られます。', '時計塔の職人', NPC_IMAGES.artisan),
      hero('労働安全衛生法を守ろう。', 'ally'),
      narrator('教育テーマ: 労働安全衛生法の遵守'),
      narrator('第7話「代わりのいない恐怖」英雄への依存が組織を弱める。'),
      ally('一人に頼るほど、崩壊が早まります。', '現場監督', NPC_IMAGES.guard),
      hero('ワークシェアリングで支える。', 'ally'),
      narrator('教育テーマ: ワークシェアリングの概念'),
      narrator('第8話「効率の魔法」短時間で成果を出す知恵。'),
      ally('長く働くより、賢く働きたい。', '時計塔の職人', NPC_IMAGES.artisan),
      hero('生産性向上は持続の鍵だ。', 'ally'),
      narrator('教育テーマ: 労働生産性の向上と効率化'),
      narrator('第9話「決戦! 時を奪う魔」人の時間を奪うボスが出現。'),
      enemy('お前たちの時間はすべて私のものだ!', '時を奪う魔', ENEMY_IMAGE),
      hero('時間搾取は人権侵害だ!', 'enemy'),
      narrator('教育テーマ: 時間搾取の否定・人権尊重'),
      narrator('第10話「安らぎの鐘」休息が王国の未来を豊かにする。'),
      ally('休めるようになり、笑顔が戻りました。', '時計塔の職人', NPC_IMAGES.artisan),
      hero('ワークライフバランスが王国を支える。', 'ally'),
      narrator('教育テーマ: ワークライフバランスの実現'),
    ],
    stage: '狂った歯車の時計塔',
    monster: '怠惰族(スロース)',
    scenario: '過重労働と健康破壊の浄化',
    playerRole: '休息と分業で時計塔を正す',
    cleared: false,
    order: 5,
    quizTriggers: [3, 7, 11, 15, 19, 23, 27, 31, 35, 39],
    ally: {
      name: '時計塔の職人',
      image: getCharacterImage('時計塔の職人'),
    },
    enemy: {
      name: '時を奪う魔',
      image: getCharacterImage('時を奪う魔'),
    },
  },
  {
    id: 'final',
    title: '終章',
    subtitle: '成果至上主義の魔王',
    category: '総合倫理・CSR',
    narration: [
      narrator('第1話「王城の変貌」効率だけを追い、心を捨てた城が現れる。'),
      ally('短期利益に偏れば王国は崩れます。', '大賢者アウレリア', NPC_IMAGES.sage),
      hero('長期的価値を守る道を選ぶ。', 'ally'),
      narrator('教育テーマ: 短期的利益と長期的価値'),
      narrator('第2話「誘惑のささやき」魔王がルール放棄を囁く。'),
      enemy('規則を捨てれば一瞬で勝てるぞ。', '魔王コンプラ・ブレイカー', ENEMY_IMAGE),
      hero('誘惑は誠実さを試す罠だ。', 'enemy'),
      narrator('教育テーマ: コンプライアンスの誘惑と罠'),
      narrator('第3話「過去の罪との対面」小さな嘘が心に影を落とす。'),
      ally('誠実さこそ守護者の力です。', '大賢者アウレリア', NPC_IMAGES.sage),
      hero('インテグリティを貫く。', 'ally'),
      narrator('教育テーマ: 誠実さ（インテグリティ）'),
      narrator('第4話「守護者の葛藤」勝利とルールの板挟み。'),
      enemy('ルールを捨てねば勝てぬぞ。', '魔王コンプラ・ブレイカー', ENEMY_IMAGE),
      hero('倫理的ジレンマを乗り越える。', 'enemy'),
      narrator('教育テーマ: 倫理的ジレンマの解消'),
      narrator('第5話「全分野の共鳴」救った仲間がそれぞれの正義を示す。'),
      ally('私たちの正義はあなたと共にある。', '五つの聖域の仲間', NPC_IMAGES.steward),
      hero('ステークホルダーと協調して進む。', 'ally'),
      narrator('教育テーマ: ステークホルダーとの協調'),
      narrator('第6話「倫理の防壁」結果至上の攻撃を誠実さで弾く。'),
      enemy('結果がすべてだ! 救いなど不要!', '魔王コンプラ・ブレイカー', ENEMY_IMAGE),
      hero('CSRを守る防壁で耐える。', 'enemy'),
      narrator('教育テーマ: 企業の社会的責任（CSR）'),
      narrator('第7話「最後の審判への道」学びの成果が道を拓く。'),
      ally('これまでの選択が光となる。', '大賢者アウレリア', NPC_IMAGES.sage),
      hero('学び続けた証を示す。', 'ally'),
      narrator('教育テーマ: 継続的な学びの成果'),
      narrator('第8話「魔王の正体」かつての守護者の悲劇が語られる。'),
      ally('手段を誤れば、正義も狂う。', '大賢者アウレリア', NPC_IMAGES.sage),
      hero('目的と手段を見失わない。', 'ally'),
      narrator('教育テーマ: 目的と手段の履き違え防止'),
      narrator('第9話「最終決戦!」複合不祥事の連鎖に挑む。'),
      enemy('全分野の混沌でお前を試す!', '魔王コンプラ・ブレイカー', ENEMY_IMAGE),
      hero('総合判断力で乗り越える!', 'enemy'),
      narrator('教育テーマ: 総合的な判断力・リーダーシップ'),
      narrator('第10話「不滅の誠実」魔王を浄化し、新しい王国を再建。'),
      ally('誠実が王国の未来を照らしました。', '五つの聖域の仲間', NPC_IMAGES.steward),
      hero('持続可能な社会を守り抜く。', 'ally'),
      narrator('教育テーマ: 持続可能な社会（ESG）への貢献'),
    ],
    stage: '王城・玉座の間',
    monster: '魔王コンプラ・ブレイカー',
    scenario: '成果至上主義と誠実の最終決戦',
    playerRole: '全分野の学びで魔王を浄化する',
    cleared: false,
    order: 6,
    quizTriggers: [3, 7, 11, 15, 19, 23, 27, 31, 35, 39],
    ally: {
      name: '大賢者アウレリア',
      image: getCharacterImage('大賢者アウレリア'),
    },
    enemy: {
      name: '魔王コンプラ・ブレイカー',
      image: getCharacterImage('魔王コンプラ・ブレイカー'),
    },
  },
];

/**
 * チャプターIDからチャプター情報を取得
 */
export function getChapter(id: string): Chapter | undefined {
  return chapters.find((chapter) => chapter.id === id);
}

/**
 * 全チャプターを取得
 */
export function getAllChapters(): Chapter[] {
  return chapters;
}

/**
 * 次のチャプターを取得
 */
export function getNextChapter(currentId: string): Chapter | undefined {
  const currentChapter = getChapter(currentId);
  if (!currentChapter) return undefined;

  return chapters.find((chapter) => chapter.order === currentChapter.order + 1);
}
